name: Build and test

on: [push, pull_request]

#env:
#  UBSAN_OPTIONS: print_stacktrace=1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shogo82148/actions-setup-perl@v1
#      - name: Install dependencies
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y libperl-dev
      - name: Clone source
        run: |
          git clone https://github.com/Infinoid/svn-bisect.git
      - name: Install Dependencies
        run: |
          export PERL_MM_USE_DEFAULT=1
          cd svn-bisect
          cpan -fi Module::Build
          cpan -fi PAR::Packer
      - name: Configure
        run: |
          cd svn-bisect
          perl Build.PL
          ls -al
          ./Build installdeps
      - name: Build
        run: |
          cd svn-bisect
          pp -o svn-bisect ./bin/svn-bisect
          ls -al
      - uses: actions/upload-artifact@v4
        with:
          name: svn-bisect
          path: svn-bisect/svn-bisect
          compression-level: 0
